server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    username: root
    password: root
    url: jdbc:mysql://location:3306/springboot5b?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver